adding questions
JupiterOne/jupiterone-alert-rules pull request #130
Opened 2024-09-10 21:56 UTC by mikiodehartj1

## QA Checklist

### Alerts Rule Packs

- [ ] IF THIS CONTENT NEEDS TO BE RELEASED - is the package version in the package.json bumped?
- [ ] Does a related alert already exist, and should it be tweaked or added to instead?
- [ ] Test each query to make sure it works
- [ ] Look for hardcoded variables/parameter values in the query
- [ ] Consider Severity for Alerts
- [ ] Spellcheck
- [ ] Use all caps for J1QL keywords and relationship classes
- [ ] Upload the alerts rule pack JSON into JupiterOne to validate

2024-09-11 00:16 UTC, SeaBlooms requested changes
couple updates then we can get this pushed out

2024-09-11 00:16 UTC, SeaBlooms commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND azure_subscription THAT RELATES TO (azure_role_definition|azure_role_assignment) WITH actions ~= 'owner' OR actions ~= 'contributor'",
query duplicate from 'execution-cloud-administration-command-privileged-account-management-azure'

2024-09-11 00:16 UTC, SeaBlooms commented on rule-packs/mitre-attck-execution-attack-paths.json
> +      "name": "execution-command-and-scripting-interpreter-execution-prevention-application-control-assessment",
add '-azure' to name

2024-09-11 00:16 UTC, SeaBlooms commented on rule-packs/mitre-attck-execution-attack-paths.json
> +      "name": "execution-command-and-scripting-interpreter-execution-prevention-application-control-policy",
add '-azure' to name

2024-09-13 16:01 UTC, SeaBlooms requested changes

2024-09-13 16:25 UTC, erincrawford commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND aws_iam_user (THAT RELATES TO aws_iam_role)? THAT ASSIGNED aws_iam_policy THAT RELATES TO as rel (aws_lambda_function|aws_lambda) WHERE rel.actions ~= ('lambda:CreateFunction
Would "lambda:*" need to be included?

2024-09-13 16:55 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND (Person|User) THAT !COMPELTED Training WITH required = true",
Corrected

2024-09-13 16:56 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND (Person|User) THAT !COMPELTED Training WITH required = true",
Corrected

2024-09-13 16:59 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND (Person|User) THAT !COMPELTED Training WITH required = true",
Corrected

2024-09-13 16:59 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +      "alertLevel": "HIGH"
Corrected

2024-09-13 17:00 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +      "alertLevel": "HIGH"
Corrected

2024-09-13 17:13 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND Container THAT !HAS Assessment",
Deleting question - Can't find a working example

2024-09-13 17:22 UTC, mikiodehartj1 commented on rule-packs/mitre-attck-execution-attack-paths.json
> +          "query": "FIND aws_iam_user (THAT RELATES TO aws_iam_role)? THAT ASSIGNED aws_iam_policy THAT RELATES TO as rel (aws_lambda_function|aws_lambda) WHERE rel.actions ~= ('lambda:CreateFunction
adding

2024-09-13 17:48 UTC, SeaBlooms approved these changes

2024-09-13 17:50 UTC, merged