Add AWS Privilege Escalation Rule Pack
JupiterOne/jupiterone-alert-rules pull request #83
Opened 2023-08-22 02:58 UTC by geovannimp

## QA Checklist

### Alerts Rule Packs
- [x] Does a related alert already exist, and should it be tweaked or added to instead?
- [ x Test each query to make sure it works
- [x] Look for hardcoded variables/parameter values in the query
- [x] Consider Severity for Alerts
- [x] Spellcheck
- [x] Use all caps for J1QL keywords and relationship classes
- [x] Upload the alerts rule pack JSON into JupiterOne to validate

2023-08-22 16:21 UTC, ajahoda requested changes

2023-08-22 16:21 UTC, ajahoda commented on rule-packs/aws-privilege-escalation.json
> +        "query": "FIND User\n  (THAT HAS aws_iam_group)?\n  (THAT ASSIGNED aws_iam_role)?\n  (THAT TRUSTS << aws_iam_role)?\n  THAT ASSIGNED AccessPolicy\n  THAT ALLOWS as perm * aws_glue\nWHERE perm
Typo in query, need to remove the `*` in `THAT ALLOWS as perm * aws_glue`.

That line should be `THAT ALLOWS as perm aws_glue`

2023-08-22 19:04 UTC, geovannimp commented
@ajahoda Can I get a review again?

2023-08-23 16:36 UTC, ajahoda approved these changes

2023-08-23 16:46 UTC, merged